include "skeleton_common.asy";

real soff = 0.5;
point dd = d + mov(d, e, ddir, soff);
point ee = e + mov(e, f, edir, soff);
point ff = f + mov(f, g, fdir, soff);
point gg = g + mov(g, h, gdir, soff);
point hh = h + mov(h, a, hdir, soff);
point aa = a + mov(a, b, adir, soff);
point bb = b + mov(b, c, bdir, soff);
point cc = c + mov(c, d, cdir, soff);
real soff0 = 1;
point dd0 = d + mov(d, e, ddir, soff0);
point ee0 = e + mov(e, f, edir, soff0);
point ff0 = f + mov(f, g, fdir, soff0);
point gg0 = g + mov(g, h, gdir, soff0);
point hh0 = h + mov(h, a, hdir, soff0);
point aa0 = a + mov(a, b, adir, soff0);
point bb0 = b + mov(b, c, bdir, soff0);
point cc0 = c + mov(c, d, cdir, soff0);

path coast0 = aa--bb--cc--dd--ee--ff--gg--hh--cycle;
path coast1 = aa0--bb0--cc0--dd0--ee0--ff0--gg0--hh0--cycle;

draw(coast0, green, EndArrow(5, position=0.8));
draw(coast1, cyan, EndArrow(5, position=0.8));
draw(a--((a + oa) * 0.5), blue + linewidth(1.2));
draw(coastline, solid+linewidth(1.2)+red);
label("$\mathrm{TC}_x=0$", a+((oa-a) * 0.5), NW, blue);
label("$\mathrm{TC}_y=0$", (c + d) * 0.5, NE, red);
draw(Label("$l(y_0)$", 0), (point(coast0, 4.5) + (1,0))--point(coast0, 4.5), green); 
draw(Label("$l(y_1)$", 0), (point(coast1, 4.2) + (1,0))--point(coast1, 4.2), cyan); 

dot("$a$",a,S);
dot("$b$",b,N);
dot("$c$",c,N);
dot("$d$",d,NE);
dot("$e$",e,W);
dot("$f$",f,W);
dot("$g$",g,S);
dot("$h$",h,S);
dot("$k$",k,W);
dot("$l$",l,E);
draw(c--k,dashed);
draw(d--k,dashed);
draw(b--l,dashed);
draw(k--l,dashed);
draw(l--ol,dashed);
draw(a--oa,dashed);
draw(h--oh,dashed);
draw(g--og,dashed);
draw(f--of,dashed);
draw(e--oe,dashed);
